import Head from 'next/head'
import { Inter } from '@next/font/google'
import '@/styles/globals.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [query, setQuery] = useState('');
  const [weather, setWeather] = useState({});

  const api = {
    key: process.env.NEXT_APP_WEATHER_API_KEY,
    base: "https://api.openweathermap.org/data/2.5/"
  }

  return (
    <>
      <Head>

        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <main>
      </main>
    </>
  )
}
